version: '2'
services:
  app:
    build: .
    volumes:
      - ".:/var/www/app"
    ports:
      - "8085:8085"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
